In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
TARGET_FOLDER = "intermediate-data/"
SOURCE_FOLDER = "raw-data/"
SEARCH_YEARS = ['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']

In [3]:
# standardizes team name for indexing
def standardize_nfl_team_name (original_series) : 
    converted_team_names = []
    for raw_content in original_series :
        new_team_name = ''
        if raw_content == "Eagles" or raw_content == "PHI" :
            new_team_name =  "Philadelphia Eagles"
        elif raw_content == "Seahawks" or raw_content == "SEA" :
            new_team_name =  "Seattle Seahawks"
        elif raw_content == "Titans" or raw_content == "TEN" :
            new_team_name =  "Tennessee Titans"
        elif raw_content == "Broncos" or raw_content == "DEN" :
            new_team_name =  "Denver Broncos"
        elif raw_content == "Giants" or raw_content == "NYG" :
            new_team_name =  "New York Giants"
        elif raw_content == "Texans" or raw_content == "HOU" :
            new_team_name =  "Houston Texans"
        elif raw_content == "Saints" or raw_content == "NO" :
            new_team_name =  "New Orleans Saints"
        elif raw_content == "Vikings" or raw_content == "MIN" :
            new_team_name =  "Minnesota Vikings"
        elif raw_content == "Chargers" or raw_content == "LAC" :
            new_team_name =  "Los Angeles Chargers"
        elif raw_content == "Falcons" or raw_content == "ATL" :
            new_team_name =  "Atlanta Falcons"
        elif raw_content == "Lions" or raw_content == "DET" :
            new_team_name =  "Detroit Lions"
        elif raw_content == "49ers" or raw_content == "SF" :
            new_team_name =  "San Francisco 49ers"
        elif raw_content == "Jets" or raw_content == "NYJ" :
            new_team_name =  "New York Jets"
        elif raw_content == "Packers" or raw_content == "GB" :
            new_team_name =  "Green Bay Packers"
        elif raw_content == "Patriots" or raw_content == "NE" :
            new_team_name =  "New England Patriots"
        elif raw_content == "Commanders" or raw_content == "WAS" :
            new_team_name =  "Washington Commanders"
        elif raw_content == "Bears" or raw_content == "CHI" :
            new_team_name =  "Chicago Bears"
        elif raw_content == "Panthers" or raw_content == "CAR" :
            new_team_name =  "Carolina Panthers"
        elif raw_content == "Cardinals" or raw_content == "ARI" :
            new_team_name =  "Arizona Cardinals"
        elif raw_content == "Cowboys" or raw_content == "DAL" :
            new_team_name =  "Dallas Cowboys"
        elif raw_content == "Chiefs" or raw_content == "KC" :
            new_team_name =  "Kansas City Chiefs"
        elif raw_content == "Colts" or raw_content == "IND" :
            new_team_name =  "Indianapolis Colts"
        elif raw_content == "Rams" or raw_content == "LA" :
            new_team_name =  "Los Angeles Rams"
        elif raw_content == "Buccaneers" or raw_content == "TB" :
            new_team_name =  "Tampa Bay Buccaneers"
        elif raw_content == "Steelers" or raw_content == "PIT" :
            new_team_name =  "Pittsburgh Steelers"
        elif raw_content == "Jaguars" or raw_content == "JAX" :
            new_team_name =  "Jacksonville Jaguars"
        elif raw_content == "Bengals" or raw_content == "CIN" :
            new_team_name =  "Cincinnati Bengals"
        elif raw_content == "Ravens" or raw_content == "BAL" :
            new_team_name =  "Baltimore Ravens"
        elif raw_content == "Bills" or raw_content == "BUF" :
            new_team_name = "Buffalo Bills"
        elif raw_content == "Dolphins" or raw_content == "MIA" :
            new_team_name =  "Miami Dolphins"
        elif raw_content == "Browns" or raw_content == "CLE" :
            new_team_name =  "Cleveland Browns"
        elif raw_content == "Raiders" or raw_content == "LV" :
            new_team_name =  "Las Vegas Raiders"
        else :
            raise Exception(f"No matching index found for [{raw_content}]")

        converted_team_names.append(new_team_name)

    return converted_team_names

In [4]:
# Combine nfl team spending data sets into one data set while converting money-string to numeric value
def create_nfl_team_spending_dataframe () :
    final_df = pd.DataFrame()
    for search_year in SEARCH_YEARS :
        # load CSV
        df = pd.read_csv(f"{SOURCE_FOLDER}nfl_team_spending_{search_year}_table.csv")

        df_columns = df.columns

        for col in df_columns :
            if col == 'Team' :
                # standardize team names
                df[col] = standardize_nfl_team_name(df[col])
            else :
                # Remove currency symbols and commas, then convert to float
                df[col] = df[col].replace(r'[$,]', '', regex=True).astype(int)

                # normalize columns
                df.rename(columns={col: f"{col}_COST"}, inplace=True)

        # add year as column
        df['Year'] = search_year

        final_df = pd.concat([final_df, df], ignore_index=True)

    # reindex
    final_df.reset_index(drop=True)
    final_df.drop(df.columns[df.columns.str.contains('unnamed', case=False)], axis=1, inplace=True)


    return final_df

In [5]:
nfl_team_spending_df = create_nfl_team_spending_dataframe ()
nfl_team_spending_df.head(65)

,Team,QB_COST,RB_COST,WR_COST,TE_COST,OL_COST,Offense_COST,IDL_COST,EDGE_COST,LB_COST,S_COST,CB_COST,Defense_COST,Year
0,Philadelphia Eagles,13385137,10203112,19241989,5509036,25664899,74004173,5264666,10241101,10004817,6920158,6032738,38463480,2013
1,Seattle Seahawks,1557085,10799653,16831423,12778788,27955261,69922210,7701509,25013832,7377232,8579619,3507877,52180069,2013
2,Tennessee Titans,6336958,15376098,12686896,6979500,26721984,68101436,6496528,8776293,5740835,10777066,9602477,41393199,2013
3,Denver Broncos,18716295,5070632,10120554,8013902,25754095,67675478,6880138,10234767,8030669,5894346,17559225,48599145,2013
4,New York Giants,21998400,5036739,8677626,2998913,24235900,62947578,5118995,9523813,7916847,12704990,11202110,46466755,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Buffalo Bills,4663940,8362867,8979223,4489668,14455361,40951059,16611040,13270000,5414838,10503423,7069748,52869049,2014
61,Miami Dolphins,5859205,2412352,8242874,6007127,17575011,40096569,15944118,11848139,9006508,5027138,13351955,55177858,2014
62,Cleveland Browns,4171299,2200883,5666354,2620527,23789034,38448097,19697955,14276906,7765000,2500318,10928931,55169110,2014
63,Las Vegas Raiders,1146517,11735884,4609651,1496363,10275023,29263438,5163512,2078750,6548030,6764294,6782330,27336916,2014
64,Philadelphia Eagles,13385137,10203112,19241989,5509036,25664899,74004173,5264666,10241101,10004817,6920158,6032738,38463480,2015

In [6]:
nfl_team_spending_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Team          320 non-null    object
 1   QB_COST       320 non-null    int32
 2   RB_COST       320 non-null    int32
 3   WR_COST       320 non-null    int32
 4   TE_COST       320 non-null    int32
 5   OL_COST       320 non-null    int32
 6   Offense_COST  320 non-null    int32
 7   IDL_COST      320 non-null    int32
 8   EDGE_COST     320 non-null    int32
 9   LB_COST       320 non-null    int32
 10  S_COST        320 non-null    int32
 11  CB_COST       320 non-null    int32
 12  Defense_COST  320 non-null    int32
 13  Year          320 non-null    object
dtypes: int32(12), object(2)
memory usage: 20.1+ KB

In [7]:
# Save results in file: intermediate/nfl_team_spending_2013_2022.csv
nfl_team_spending_df.to_csv(f"{TARGET_FOLDER}nfl_team_spending_2013_2022.csv", index=True)

In [8]:
# clean the NFL_team_playoff_perc_win_data.csv data file.
df = pd.read_csv(f"{SOURCE_FOLDER}NFL_team_playoff_perc_win_data.csv")
# df.rename(columns={'PD':'PointDifferential', 'FGM':'MadeFG', 'RedZonePerc':'OffDrivePercToRedZone', 'possperG':'TimeOfPoss'})

# add column marking teams with a value of 1.0 when they made the playoffs
df['MadePlayoffs'] = df['playoff_win_perc'].where(df['playoff_win_perc'] == 0, other=1)

# drop rows where year is outside of range including 2013 to 2022
nfl_team_yearly_win_stats_df = df.query('Year >= 2013 and Year <= 2021')[['MadePlayoffs', 'Year', 'Team']]

# add playoff data for 2022
for team in df.query('Year == 2021')['Team'] :
    playoffFlag = 0
    if (team == 'Philadelphia Eagles' or team == 'San Francisco 49ers' or team == 'Minnesota Vikings' or team == 'Tampa Bay Buccaneers'
        or team == 'Dallas Cowboys' or team == 'New York Giants' or team == 'Seattle Seahawks' or team == 'Cincinnati Bengals'
        or team == 'Jacksonville Jaguars' or team == 'Los Angeles Chargers' or team == 'Baltimore Ravens' or team == 'Buffalo Bills'
        or team == 'Miami Dolphins' or team == 'Kansas City Chiefs'
    ) :
        playoffFlag = 1

    nfl_team_yearly_win_stats_df = \
        pd.concat([pd.DataFrame([[playoffFlag, 2022, team]], columns=['MadePlayoffs', 'Year', 'Team'])
                , nfl_team_yearly_win_stats_df]
                , ignore_index=True)


nfl_team_yearly_win_stats_df.head(65)

    MadePlayoffs  Year                  Team
0            1.0  2022      Seattle Seahawks
1            1.0  2022   San Francisco 49ers
2            0.0  2022     Arizona Cardinals
3            0.0  2022      Los Angeles Rams
4            0.0  2022     Carolina Panthers
..           ...   ...                   ...
60           1.0  2013      Seattle Seahawks
61           1.0  2013   San Francisco 49ers
62           0.0  2013     Arizona Cardinals
63           0.0  2013      Los Angeles Rams
64           1.0  2014  New England Patriots

[65 rows x 3 columns]

In [9]:
nfl_team_yearly_win_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MadePlayoffs  320 non-null    float64
 1   Year          320 non-null    int64
 2   Team          320 non-null    object
dtypes: float64(1), int64(1), object(1)
memory usage: 7.6+ KB

In [10]:
# Save results in file: intermediate/nfl_team_playoffs_2013_2022.csv
nfl_team_yearly_win_stats_df.to_csv(f"{TARGET_FOLDER}nfl_team_playoffs_2013_2022.csv", index=True)

In [11]:
# Normalize NFL team statistics data set
def create_nfl_team_stats_dataframe () :
    # load CSV
    df = pd.read_csv(f"{SOURCE_FOLDER}nfl-team-statistics.csv")

    # normalize column names
    df.rename(columns={'season':'Year', 'team':'Team'}, inplace=True)
    df.query('Year >= 2013 and Year <= 2022', inplace=True)

    # standardize team names
    df['Team'] = standardize_nfl_team_name(df['Team'])

    # reindex
    df.reset_index(drop=True, inplace=True)

    return df

In [12]:
# Save results in file: intermediate/nfl_team_stats_2013_2022.csv
nfl_team_yearly_stats_df = create_nfl_team_stats_dataframe ()
nfl_team_yearly_stats_df.to_csv(f"{TARGET_FOLDER}nfl_team_stats_2013_2022.csv", index=True)
nfl_team_yearly_stats_df.head(65)

,Year,Team,offense_completion_percentage,offense_total_yards_gained_pass,offense_total_yards_gained_run,offense_ave_yards_gained_pass,offense_ave_yards_gained_run,offense_total_air_yards,offense_ave_air_yards,offense_total_yac,...,defense_ave_wpa_pass,defense_ave_wpa_run,defense_success_rate_pass,defense_success_rate_run,points_scored,points_allowed,wins,losses,ties,score_differential
0,2013,Arizona Cardinals,0.588331,4002,1562,6.486224,3.875931,5284,9.221640,1756,...,-0.000926,-0.003678,0.428999,0.361878,379,324,10,6,0,55
1,2013,Atlanta Falcons,0.632479,4253,1263,6.058405,4.022293,4482,6.821918,2132,...,0.002547,0.001237,0.478102,0.406742,353,443,4,12,0,-90
2,2013,Baltimore Ravens,0.543413,3594,1337,5.380240,3.213942,5781,9.369530,1751,...,0.000778,-0.002010,0.411467,0.373239,320,352,8,8,0,-32
3,2013,Buffalo Bills,0.523643,3107,2338,5.441331,4.428030,4506,8.648752,1508,...,-0.003505,-0.000593,0.378029,0.368421,339,388,6,10,0,-49
4,2013,Carolina Panthers,0.569201,3043,2043,5.931774,4.365385,4238,9.017021,1613,...,-0.002219,-0.004016,0.439103,0.376471,366,241,12,4,0,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2014,San Francisco 49ers,0.541744,3063,2192,5.682746,4.817582,4737,9.726899,1393,...,-0.000917,-0.001690,0.433219,0.374359,306,340,8,8,0,-34
61,2014,Tampa Bay Buccaneers,0.520761,3297,1375,5.704152,3.906250,5488,10.433460,1154,...,0.003890,-0.000505,0.502513,0.373068,277,410,2,14,0,-133
62,2014,Tennessee Titans,0.533929,3412,1460,6.092857,4.231884,4701,9.217647,1628,...,0.002512,0.001328,0.469178,0.397566,254,438,2,14,0,-184
63,2014,Washington Commanders,0.601653,4047,1697,6.689256,4.285354,4223,7.720293,2543,...,0.005929,-0.001102,0.464029,0.370460,301,438,4,12,0,-137
64,2015,Arizona Cardinals,0.605489,4616,1946,7.917667,4.611374,6084,10.942446,1782,...,0.000101,-0.003341,0.419935,0.368852,489,313,13,3,0,176

In [13]:
nfl_team_yearly_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 56 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Year                             320 non-null    int64
 1   Team                             320 non-null    object
 2   offense_completion_percentage    320 non-null    float64
 3   offense_total_yards_gained_pass  320 non-null    int64
 4   offense_total_yards_gained_run   320 non-null    int64
 5   offense_ave_yards_gained_pass    320 non-null    float64
 6   offense_ave_yards_gained_run     320 non-null    float64
 7   offense_total_air_yards          320 non-null    int64
 8   offense_ave_air_yards            320 non-null    float64
 9   offense_total_yac                320 non-null    int64
 10  offense_ave_yac                  320 non-null    float64
 11  offense_n_plays_pass             320 non-null    int64
 12  offense_n_plays_run              320 non-null    int64
 13  offense_n_interceptions          320 non-null    int64
 14  offense_n_fumbles_lost_pass      320 non-null    int64
 15  offense_n_fumbles_lost_run       320 non-null    int64
 16  offense_total_epa_pass           320 non-null    float64
 17  offense_total_epa_run            320 non-null    float64
 18  offense_ave_epa_pass             320 non-null    float64
 19  offense_ave_epa_run              320 non-null    float64
 20  offense_total_wpa_pass           320 non-null    float64
 21  offense_total_wpa_run            320 non-null    float64
 22  offense_ave_wpa_pass             320 non-null    float64
 23  offense_ave_wpa_run              320 non-null    float64
 24  offense_success_rate_pass        320 non-null    float64
 25  offense_success_rate_run         320 non-null    float64
 26  defense_completion_percentage    320 non-null    float64
 27  defense_total_yards_gained_pass  320 non-null    int64
 28  defense_total_yards_gained_run   320 non-null    int64
 29  defense_ave_yards_gained_pass    320 non-null    float64
 30  defense_ave_yards_gained_run     320 non-null    float64
 31  defense_total_air_yards          320 non-null    int64
 32  defense_ave_air_yards            320 non-null    float64
 33  defense_total_yac                320 non-null    int64
 34  defense_ave_yac                  320 non-null    float64
 35  defense_n_plays_pass             320 non-null    int64
 36  defense_n_plays_run              320 non-null    int64
 37  defense_n_interceptions          320 non-null    int64
 38  defense_n_fumbles_lost_pass      320 non-null    int64
 39  defense_n_fumbles_lost_run       320 non-null    int64
 40  defense_total_epa_pass           320 non-null    float64
 41  defense_total_epa_run            320 non-null    float64
 42  defense_ave_epa_pass             320 non-null    float64
 43  defense_ave_epa_run              320 non-null    float64
 44  defense_total_wpa_pass           320 non-null    float64
 45  defense_total_wpa_run            320 non-null    float64
 46  defense_ave_wpa_pass             320 non-null    float64
 47  defense_ave_wpa_run              320 non-null    float64
 48  defense_success_rate_pass        320 non-null    float64
 49  defense_success_rate_run         320 non-null    float64
 50  points_scored                    320 non-null    int64
 51  points_allowed                   320 non-null    int64
 52  wins                             320 non-null    int64
 53  losses                           320 non-null    int64
 54  ties                             320 non-null    int64
 55  score_differential               320 non-null    int64
dtypes: float64(30), int64(25), object(1)
memory usage: 140.1+ KB

In [14]:
# concatenate dataframes based on Year and team
playoff_df = pd.read_csv(f"{TARGET_FOLDER}nfl_team_playoffs_2013_2022.csv")
spending_df = pd.read_csv(f"{TARGET_FOLDER}nfl_team_spending_2013_2022.csv")
stats_df = pd.read_csv(f"{TARGET_FOLDER}nfl_team_stats_2013_2022.csv")

merged_po_spend_df = pd.merge(playoff_df, spending_df, on=['Year', 'Team'], how='inner')
all_stats_df = pd.merge(merged_po_spend_df, stats_df, on=['Year', 'Team'], how='inner')

# reindex
all_stats_df.reset_index(drop=True, inplace=True)
all_stats_df.drop(all_stats_df.columns[all_stats_df.columns.str.contains('Unnamed:', case=False)], axis=1, inplace=True)

# save to csv
all_stats_df.to_csv(f"{TARGET_FOLDER}nfl_team_all_stats_2013_2022.csv", index=True)

In [15]:
# show all stats
all_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 69 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   MadePlayoffs                     320 non-null    float64
 1   Year                             320 non-null    int64
 2   Team                             320 non-null    object
 3   QB_COST                          320 non-null    int64
 4   RB_COST                          320 non-null    int64
 5   WR_COST                          320 non-null    int64
 6   TE_COST                          320 non-null    int64
 7   OL_COST                          320 non-null    int64
 8   Offense_COST                     320 non-null    int64
 9   IDL_COST                         320 non-null    int64
 10  EDGE_COST                        320 non-null    int64
 11  LB_COST                          320 non-null    int64
 12  S_COST                           320 non-null    int64
 13  CB_COST                          320 non-null    int64
 14  Defense_COST                     320 non-null    int64
 15  offense_completion_percentage    320 non-null    float64
 16  offense_total_yards_gained_pass  320 non-null    int64
 17  offense_total_yards_gained_run   320 non-null    int64
 18  offense_ave_yards_gained_pass    320 non-null    float64
 19  offense_ave_yards_gained_run     320 non-null    float64
 20  offense_total_air_yards          320 non-null    int64
 21  offense_ave_air_yards            320 non-null    float64
 22  offense_total_yac                320 non-null    int64
 23  offense_ave_yac                  320 non-null    float64
 24  offense_n_plays_pass             320 non-null    int64
 25  offense_n_plays_run              320 non-null    int64
 26  offense_n_interceptions          320 non-null    int64
 27  offense_n_fumbles_lost_pass      320 non-null    int64
 28  offense_n_fumbles_lost_run       320 non-null    int64
 29  offense_total_epa_pass           320 non-null    float64
 30  offense_total_epa_run            320 non-null    float64
 31  offense_ave_epa_pass             320 non-null    float64
 32  offense_ave_epa_run              320 non-null    float64
 33  offense_total_wpa_pass           320 non-null    float64
 34  offense_total_wpa_run            320 non-null    float64
 35  offense_ave_wpa_pass             320 non-null    float64
 36  offense_ave_wpa_run              320 non-null    float64
 37  offense_success_rate_pass        320 non-null    float64
 38  offense_success_rate_run         320 non-null    float64
 39  defense_completion_percentage    320 non-null    float64
 40  defense_total_yards_gained_pass  320 non-null    int64
 41  defense_total_yards_gained_run   320 non-null    int64
 42  defense_ave_yards_gained_pass    320 non-null    float64
 43  defense_ave_yards_gained_run     320 non-null    float64
 44  defense_total_air_yards          320 non-null    int64
 45  defense_ave_air_yards            320 non-null    float64
 46  defense_total_yac                320 non-null    int64
 47  defense_ave_yac                  320 non-null    float64
 48  defense_n_plays_pass             320 non-null    int64
 49  defense_n_plays_run              320 non-null    int64
 50  defense_n_interceptions          320 non-null    int64
 51  defense_n_fumbles_lost_pass      320 non-null    int64
 52  defense_n_fumbles_lost_run       320 non-null    int64
 53  defense_total_epa_pass           320 non-null    float64
 54  defense_total_epa_run            320 non-null    float64
 55  defense_ave_epa_pass             320 non-null    float64
 56  defense_ave_epa_run              320 non-null    float64
 57  defense_total_wpa_pass           320 non-null    float64
 58  defense_total_wpa_run            320 non-null    float64
 59  defense_ave_wpa_pass             320 non-null    float64
 60  defense_ave_wpa_run              320 non-null    float64
 61  defense_success_rate_pass        320 non-null    float64
 62  defense_success_rate_run         320 non-null    float64
 63  points_scored                    320 non-null    int64
 64  points_allowed                   320 non-null    int64
 65  wins                             320 non-null    int64
 66  losses                           320 non-null    int64
 67  ties                             320 non-null    int64
 68  score_differential               320 non-null    int64
dtypes: float64(31), int64(37), object(1)
memory usage: 172.6+ KB